version: '1.0'

services:
  pb:
    build:
      context: ./pb
      dockerfile: Dockerfile
    container_name: pb-container
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui-container
    ports:
      - "8090:8090"
    restart: unless-stopped
  
  rp:
    image: caddy:2.7-alpine
    container_name: rp-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rp/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
